//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Animes.Club.Crawler
{
    using System;
    using System.Collections.Generic;
    
    public partial class anidb
    {
        public int id { get; set; }
        public int anidbid { get; set; }
        public string title { get; set; }
        public string type { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string related { get; set; }
        public string creators { get; set; }
        public string description { get; set; }
        public string rating { get; set; }
        public string picture { get; set; }
        public string categories { get; set; }
        public string characters { get; set; }
        public string epnos { get; set; }
        public string airdates { get; set; }
        public string episodetitles { get; set; }
        public int unixtime { get; set; }
    }
}
