//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Animes.Club.Crawler
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animes
    {
        public Animes()
        {
            this.AnimeLists = new HashSet<AnimeLists>();
            this.Tags = new HashSet<Tags>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string picture { get; set; }
        public string description { get; set; }
        public Nullable<float> rating { get; set; }
        public Nullable<int> episodes { get; set; }
    
        public virtual ICollection<AnimeLists> AnimeLists { get; set; }
        public virtual ICollection<Tags> Tags { get; set; }
    }
}
