// <auto-generated />
namespace Animes.Club.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class animedescriptionandrate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(animedescriptionandrate));
        
        string IMigrationMetadata.Id
        {
            get { return "201501240814102_anime description and rate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
