// <auto-generated />
namespace Animes.Club.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class animelistdatastructurechange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(animelistdatastructurechange));
        
        string IMigrationMetadata.Id
        {
            get { return "201501300253002_anime list data structure change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
